---
- set_fact:
    pip_exe: "{{ miniconda_home }}/envs/prod/bin/pip"

- name: install package for development
  pip: executable="{{ pip_exe }}" extra_args="--editable"
       name="/vagrant"

- name: install dev dependencies
  pip: requirements=/vagrant/requirements/dev.txt
       executable="{{ pip_exe }}"

- name: copy demo config file
  copy: src=demo.cfg dest=/home/vagrant/demo.cfg

- name: install global npm dependencies
  npm: name={{ item }} global=yes
  with_items:
    - coffee-script
    - gulp
  sudo: yes

- name: install package npm dependencies
  shell: chdir=/vagrant npm install
